/* Report / CSV / GeoJSON / PNG exports — ported from the single-file app. */
import { PRESET } from './detect'

export function stamp() { const d = new Date(); return d.toISOString().slice(0, 10) }

export function save(blob, name) {
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob); a.download = name; a.click()
  setTimeout(() => URL.revokeObjectURL(a.href), 1000)
}

export function downloadCSV(r) {
  const geo = r.coords
  let csv = 'id,pixel_x,pixel_y' + (geo ? ',x,y' : '') + '\n'
  r.full.forEach(([x, y], i) => {
    csv += (i + 1) + ',' + Math.round(x) + ',' + Math.round(y)
      + (geo ? (',' + geo[i][0].toFixed(3) + ',' + geo[i][1].toFixed(3)) : '') + '\n'
  })
  save(new Blob([csv], { type: 'text/csv' }), 'dia_' + r.mode + '_' + stamp() + '_points.csv')
}

export function downloadGeoJSON(r) {
  if (!r.coords) return
  const feats = r.coords.map((c, i) => ({
    type: 'Feature', properties: { id: i + 1 },
    geometry: { type: 'Point', coordinates: [c[0], c[1]] },
  }))
  const fc = { type: 'FeatureCollection', crs: { type: 'name', properties: { name: r.geo.crs } }, features: feats }
  save(new Blob([JSON.stringify(fc)], { type: 'application/json' }), 'dia_' + r.mode + '_' + stamp() + '_points.geojson')
}

export function downloadPNG(canvas, r) {
  canvas.toBlob(b => save(b, 'dia_' + r.mode + '_' + stamp() + '_map.png'), 'image/png')
}

export function downloadReport(canvas, r) {
  const png = canvas.toDataURL('image/png')
  const row = (k, v) => '<tr><th>' + k + '</th><td>' + v + '</td></tr>'
  const html = '<!DOCTYPE html><meta charset="utf-8"><title>DIA report — ' + r.mode + ' ' + stamp() + '</title>'
    + '<style>body{font-family:system-ui,sans-serif;max-width:900px;margin:30px auto;padding:0 20px;color:#1a1a1a}'
    + 'h1{font-size:22px}.c{font-size:46px;color:#e8551f;font-weight:700;margin:4px 0}'
    + 'table{border-collapse:collapse;margin:16px 0}th,td{border:1px solid #ddd;padding:7px 12px;text-align:left;font-size:14px}'
    + 'th{background:#f4f4f0;width:200px}img{max-width:100%;border:1px solid #ccc;margin-top:10px}'
    + 'small{color:#777}</style>'
    + '<h1>DIA — ' + (r.mode === 'palm' ? 'Oil palm plantation' : 'Nursery polybag') + ' count</h1>'
    + '<div class="c">' + r.count + ' ' + PRESET[r.mode].word + '</div>'
    + '<table>'
    + row('Date', new Date().toLocaleString())
    + row('Mapped area', r.areaHa ? r.areaHa.toFixed(2) + ' ha' : 'not available')
    + row('Density', r.density ? r.density.toFixed(1) + ' / ha' : 'not available')
    + row('Georeferenced', r.geo ? (r.geo.crs || 'yes') : 'no')
    + row('Counted within boundary', r.clipped ? 'yes — clipped to KML' : 'no — whole map')
    + row('Source resolution', r.fullW + ' × ' + r.fullH + ' px')
    + row('Detection setting', r.src + (r.thr ? ', sensitivity ' + r.thr.toFixed(2) : ''))
    + '</table>'
    + '<img src="' + png + '" alt="annotated map">'
    + '<p><small>Generated by MJM AI · DIA. Counts are estimates'
    + (r.src && r.src.indexOf('AI') === 0 ? ' from a Gemini vision model.' : ' from canopy greenness.') + '</small></p>'
  save(new Blob([html], { type: 'text/html' }), 'dia_' + r.mode + '_' + stamp() + '_report.html')
}
